Name:           ros-jade-cram-3rdparty
Version:        0.1.3
Release:        0%{?dist}
Summary:        ROS cram_3rdparty package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/cram_3rdparty
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-jade-alexandria
Requires:       ros-jade-babel
Requires:       ros-jade-cffi
Requires:       ros-jade-cl-store
Requires:       ros-jade-cl-utilities
Requires:       ros-jade-fiveam
Requires:       ros-jade-gsd
Requires:       ros-jade-gsll
Requires:       ros-jade-lisp-unit
Requires:       ros-jade-split-sequence
Requires:       ros-jade-synchronization-tools
Requires:       ros-jade-trivial-features
Requires:       ros-jade-trivial-garbage
Requires:       ros-jade-trivial-gray-streams
Requires:       ros-jade-yason
BuildRequires:  ros-jade-catkin

%description
Various 3rd party Common LISP packages for the CRAM framework.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Fri Apr 24 2015 Georg Bartels <georg.bartels@cs.uni-bremen.de> - 0.1.3-0
- Autogenerated by Bloom

