Name:           ros-indigo-yason
Version:        0.1.3
Release:        0%{?dist}
Summary:        ROS yason package

Group:          Development/Libraries
License:        BSD
URL:            http://common-lisp.net/project/yason/
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-alexandria
Requires:       ros-indigo-trivial-gray-streams
Requires:       sbcl
BuildRequires:  ros-indigo-alexandria
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-trivial-gray-streams
BuildRequires:  sbcl

%description
3rd party library: YASON

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Apr 24 2015 Lorenz Moesenlechner <moesenle@cs.tum.edu> - 0.1.3-0
- Autogenerated by Bloom

