Name:           ros-jade-gsll
Version:        0.1.3
Release:        0%{?dist}
Summary:        ROS gsll package

Group:          Development/Libraries
License:        GPL
URL:            http://common-lisp.net/project/gsll/
Source0:        %{name}-%{version}.tar.gz

Requires:       gsl
Requires:       ros-jade-cffi
Requires:       ros-jade-cl-utilities
Requires:       ros-jade-gsd
Requires:       ros-jade-trivial-garbage
Requires:       sbcl
BuildRequires:  gsl
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-cffi
BuildRequires:  ros-jade-cl-utilities
BuildRequires:  ros-jade-gsd
BuildRequires:  ros-jade-trivial-garbage
BuildRequires:  sbcl

%description
3rd party library: GSLL a GSL wrapper for common lisp

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Fri Apr 24 2015 Lorenz Moesenlechner <moesenle@cs.tum.edu> - 0.1.3-0
- Autogenerated by Bloom

